# Generated by Django 5.1.4 on 2024-12-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_formula_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
